schema:
  - https://api.spacex.land/graphql
  - src/client.schema.graphql


documents:
  - src/**/*.fragment.graphql
  - src/**/*.mutation.graphql
  - src/**/*.query.graphql
  - src/**/*.subscription.graphql

extensions:
  codegen:
    config:
      constEnums: true
      declarationKind: interface
      dedupeOperationSuffix: true
      immutableTypes: true
      namingConvention: keep
      noSchemaStitching: true
      operationResultSuffix: Data
      optionalResolveType: true
      useIndexSignature: true

    generates:
      src/schema.ts:
        - typescript
      src/:
        preset: near-operation-file
        presetConfig:
          baseTypesPath: schema.ts
          extension: .ts
        schema: client.schema.graphql
        plugins:
          - typescript-operations
          - typed-document-node
